// Run with the absolute path to an available Playwright package as the argument.
const {chromium} = require(process.argv[2] || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
  fs.mkdirSync('test-results/jobs', {recursive:true});
  const browser = await chromium.launch({headless:true, ...(process.env.PLAYWRIGHT_CHANNEL ? {channel:process.env.PLAYWRIGHT_CHANNEL} : {})});
  try {
    const context = await browser.newContext({viewport:{width:1440,height:1100}});
    const page = await context.newPage();
    const errors=[]; page.on('pageerror',e=>errors.push(e.message));
    const dataset=JSON.parse(fs.readFileSync('k8s/resume.json','utf8'));
    // Fixture the unchanged read-only API for the home-page navigation check.
    await page.route('**/api/resume',r=>r.fulfill({json:dataset}));
    await page.route('**/api/projects',r=>r.fulfill({json:dataset.projects}));
    await page.goto('http://127.0.0.1:5173/jobs');
    await page.getByRole('heading',{name:'첫 공고를 추가해 보세요'}).waitFor();
    await page.getByRole('button',{name:'예시 공고로 미리보기'}).click();
    assert.equal(await page.locator('.job-card').count(),4);
    await page.screenshot({path:'test-results/jobs/desktop.png',fullPage:true});
    await page.getByLabel('직무',{exact:true}).selectOption('DevOps');
    assert.equal(await page.locator('.job-card').count(),1);
    await page.getByRole('button',{name:'초기화',exact:true}).click();
    await page.getByLabel(/^직선거리/).selectOption('10');
    assert.equal(await page.locator('.job-card').count(),0);
    await page.getByRole('button',{name:'전체 공고 보기',exact:true}).click();
    await page.getByRole('button',{name:'플랫폼 랩 관심 공고 저장',exact:true}).click();
    await page.getByRole('button',{name:/관심 공고\s*1/}).click();
    assert.equal(await page.locator('.job-card').count(),1);
    await page.getByRole('button',{name:'경험 비교 및 상세 →',exact:true}).click();
    await page.getByRole('heading',{name:'회사 실무에서 연결되는 기술'}).waitFor();
    await page.getByRole('dialog').getByLabel(/^공고 상태/).selectOption('applied');
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('dialog').count(),0);
    await page.getByRole('button',{name:'＋ 공고 직접 추가',exact:true}).click();
    await page.getByLabel('회사명',{exact:true}).fill('검증 회사');
    await page.getByLabel('포지션',{exact:true}).fill('검증용 플랫폼 엔지니어');
    await page.getByLabel('공고 본문',{exact:true}).fill('BOSH, Grafana, Kubernetes 운영 경험');
    await page.getByRole('button',{name:'공고 추가',exact:true}).click();
    assert.equal(await page.locator('.job-card').count(),1);
    await page.reload();
    await page.getByRole('button',{name:'검증용 플랫폼 엔지니어',exact:true}).waitFor();
    await page.getByRole('link',{name:'내 이력서 관리',exact:true}).click();
    await page.getByRole('heading',{name:'내 이력서 관리',exact:true}).waitFor();
    await page.locator('input[type=file]').setInputFiles({name:'resume.txt',mimeType:'text/plain',buffer:Buffer.from('BOSH 운영 자동화 검증')});
    await page.getByText('resume.txt의 텍스트를 읽었습니다.',{exact:false}).waitFor();
    await page.getByRole('button',{name:'편집 영역에 반영'}).click();
    assert.equal(await page.getByLabel('회사 실무 경험',{exact:true}).inputValue(),'BOSH 운영 자동화 검증');
    await page.getByRole('button',{name:'추천 프로필 저장'}).click();
    await page.reload();
    assert.equal(await page.getByLabel('회사 실무 경험',{exact:true}).inputValue(),'BOSH 운영 자동화 검증');
    await page.locator('input[type=file]').setInputFiles({name:'resume.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF')});
    await page.getByText('PDF·Word 자동 분석은 아직 연결되지 않았습니다.',{exact:false}).waitFor();
    await page.getByRole('link',{name:'이력서',exact:true}).click();
    await page.getByRole('link',{name:'회사 찾기 ↗',exact:true}).waitFor();
    // Fresh context for screenshots; no test data appear in the preview.
    const clean = await browser.newContext({viewport:{width:390,height:844}});
    const mobile=await clean.newPage();
    mobile.on('pageerror',e=>errors.push(e.message));
    await mobile.goto('http://127.0.0.1:5173/jobs');
    await mobile.getByRole('button',{name:'예시 공고로 미리보기'}).click();
    assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
    await mobile.screenshot({path:'test-results/jobs/mobile.png',fullPage:true});
    await mobile.goto('http://127.0.0.1:5173/jobs/profile');
    await mobile.getByRole('heading',{name:'내 이력서 관리',exact:true}).waitFor();
    assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth <= innerWidth));
    await mobile.setViewportSize({width:1440,height:1100});
    await mobile.screenshot({path:'test-results/jobs/profile.png',fullPage:true});
    assert.deepEqual(errors,[]);
    console.log('PASS: direct routes, empty/demo states, filters, status, modal, manual posting, persistence, TXT import, PDF notice, home navigation, mobile overflow; no page errors.');
    console.log(path.resolve('test-results/jobs'));
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
