apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resume
resources:
- namespace.yaml
- rbac.yaml
- workloads.yaml
- services.yaml
- policies.yaml
- pdb.yaml
configMapGenerator:
- name: resume-data
  files:
  - resume.json
images:
- name: resume-web
  newName: ghcr.io/idk3669/resume-web
  digest: sha256:7ee51aa1e581e5a6553eff5295b0138ac3f67799175446804c8f4290f98fda60
- name: resume-api
  newName: ghcr.io/idk3669/resume-api
  digest: sha256:b94553c47ac4a34ed01dc9a415d638cf9737d1f894b89ffda94bd52f90c492aa
