apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resume
resources:
- namespace.yaml
- rbac.yaml
- workloads.yaml
- services.yaml
- policies.yaml
- pdb.yaml
configMapGenerator:
- name: resume-data
  files:
  - resume.json
images:
- name: resume-web
  newName: ghcr.io/idk3669/resume-web
  digest: sha256:9b45e8e67ed1c800f38ab304fd478277b3334b9a9b465fac8bbfd9081612665a
- name: resume-api
  newName: ghcr.io/idk3669/resume-api
  digest: sha256:213a9775dad44c1fd3765bfee369e407964aadc235cbe62b28fd4efb033ac01e
