apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: resume
resources:
  - namespace.yaml
  - rbac.yaml
  - workloads.yaml
  - services.yaml
  - policies.yaml
  - pdb.yaml
configMapGenerator:
  - name: resume-data
    files:
      - resume.json
images:
  - name: resume-web
    newName: resume-web
    newTag: 1.0.0
  - name: resume-api
    newName: resume-api
    newTag: 1.0.0
